

List<String> Renkliste= [
"GRADIENT_TYPE_GRADE_GREY",
"GRADIENT_TYPE_COOL_BLUES",
"GRADIENT_TYPE_MEGATRON",
"GRADIENT_TYPE_JSHINE",
"GRADIENT_TYPE_EVENING_SUNSHINE",
"GRADIENT_TYPE_MOONLIT_ASTEROID",
"GRADIENT_TYPE_DARK_OCEAN",
"GRADIENT_TYPE_COOL_SKY",
"GRADIENT_TYPE_YODA",
"GRADIENT_TYPE_AMIN",
"GRADIENT_TYPE_HARVEY",
"GRADIENT_TYPE_NEUROMANCER",
"GRADIENT_TYPE_AZUR_LANE",
"GRADIENT_TYPE_WITCHING_HOUR",
"GRADIENT_TYPE_FLARE",
"GRADIENT_TYPE_METAPOLIS",
"GRADIENT_TYPE_KYOO_PAL",
"GRADIENT_TYPE_KYE_MEH",
"GRADIENT_TYPE_KYOO_TAH",
"GRADIENT_TYPE_BY_DESIGN",

];